/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ifrr.ticketing.swing;

import com.ifrr.ticketing.entities.Dispositivo;
import com.ifrr.ticketing.entities.Espacio;
import com.ifrr.ticketing.entities.Incidencia;
import com.ifrr.ticketing.entities.Perfil;
import com.ifrr.ticketing.entities.Usuario;
import com.ifrr.ticketing.service.ServiceDispositivo;
import com.ifrr.ticketing.service.ServiceEspacio;
import com.ifrr.ticketing.service.ServiceIncidencia;
import com.ifrr.ticketing.service.ServiceUsuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author nakayoshi_dango
 */
public class AdminCreateIncidencia extends javax.swing.JDialog {

    private final ServiceDispositivo sd;
    private final ServiceEspacio se;
    private final ServiceUsuario su;
    private final ServiceIncidencia si;

    /**
     * Creates new form CreateIncidencia
     */
    public AdminCreateIncidencia(java.awt.Frame parent, boolean modal, ServiceDispositivo sd, ServiceEspacio se, ServiceUsuario su, ServiceIncidencia si) {
        super(parent, modal);
        this.sd = sd;
        this.se = se;
        this.su = su;
        this.si = si;
        initComponents();
        loadComboBoxData();
    }

    private void loadComboBoxData() {
        List<Dispositivo> dispositivos = sd.getAllDispositivos();
        for (Dispositivo d : dispositivos) {
            dispositivoComboBox.addItem(d.getTipo() + " " + d.getMarca() + " " + d.getModelo() + " " + d.getDescripcion());
        }

        List<Espacio> espacios = se.getAllEspacios();
        for (Espacio e : espacios) {
            espacioComboBox.addItem(e.getDescripcion());
        }
        List<Usuario> usuarios = su.getAllUsuarios();
        for (Usuario u : usuarios) {
            Set<Perfil> perfiles = u.getPerfiles();
            boolean esTecnico = false;
            boolean esGestor = false;
            boolean esUsuario = false;

            for (Perfil p : perfiles) {
                if (p.getId() == 1) {
                    esUsuario = true;
                }
                if (p.getId() == 2) {
                    esTecnico = true;
                }
                if (p.getId() == 3) {
                    esGestor = true;
                }
            }

            String item = u.getId() + ";" + u.getNombreApellidos() + ";" + u.getCorreo();

            if (esTecnico) {
                tecnicoComboBox.addItem(item);
            }
            if (esGestor) {
                gestorComboBox.addItem(item);
            }
            if (esUsuario) {
                usuarioComboBox.addItem(item);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        dispositivoComboBox = new javax.swing.JComboBox<>();
        espacioComboBox = new javax.swing.JComboBox<>();
        fEntrada = new javax.swing.JFormattedTextField();
        fCierre = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tecnicoComboBox = new javax.swing.JComboBox<>();
        gestorComboBox = new javax.swing.JComboBox<>();
        usuarioComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descSol = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descInci = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(914, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(914, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Estado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Dispositivo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Espacio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 171, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Crear Incidencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, -1, -1));

        textEstado.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 600, -1));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Tipo Incidencia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        textTipo.setPreferredSize(new java.awt.Dimension(450, 23));
        jPanel1.add(textTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 600, -1));
        jPanel1.add(dispositivoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 600, -1));
        jPanel1.add(espacioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 600, -1));

        fEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));
        fEntrada.setText(LocalDate.now().format(formatter));
        fEntrada.setPreferredSize(new java.awt.Dimension(125, 35));
        jPanel1.add(fEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, -1, -1));

        fCierre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));
        fCierre.setText(LocalDate.now().format(formatter));
        fCierre.setPreferredSize(new java.awt.Dimension(125, 35));
        jPanel1.add(fCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, -1, -1));

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Fecha Creación");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Fecha Cierre");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        jPanel1.add(tecnicoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 600, -1));

        jPanel1.add(gestorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 600, -1));

        jPanel1.add(usuarioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 600, -1));

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Técnico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Gestor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Usuario");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        descSol.setColumns(20);
        descSol.setRows(5);
        jScrollPane1.setViewportView(descSol);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 400, 200));

        descInci.setColumns(20);
        descInci.setRows(5);
        jScrollPane2.setViewportView(descInci);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 400, 200));

        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("Descripción Incidencia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel13.setForeground(new java.awt.Color(242, 242, 242));
        jLabel13.setText("Descripción Solución");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Incidencia in = new Incidencia(fEntrada.getText(), fCierre.getText(), textEstado.getText(), textTipo.getText(), su.getUsuarioById(Integer.valueOf(((String) gestorComboBox.getSelectedItem()).split(";")[0])), su.getUsuarioById(Integer.valueOf(((String) usuarioComboBox.getSelectedItem()).split(";")[0])), su.getUsuarioById(Integer.valueOf(((String) tecnicoComboBox.getSelectedItem()).split(";")[0])), descInci.getText(), descSol.getText());
        int dispositivoIndex = dispositivoComboBox.getSelectedIndex();
        int espacioIndex = espacioComboBox.getSelectedIndex();
        if (dispositivoIndex >= 0) {
            Dispositivo dispositivo = sd.getAllDispositivos().get(dispositivoIndex);
            in.setDispositivo(dispositivo);
        }
        if (espacioIndex >= 0) {
            Espacio espacio = se.getAllEspacios().get(espacioIndex);
            in.setEspacio(espacio);
        }

        in = si.createIncidencia(in);
        if (in != null) {
            dispose();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "No se pudo crear la incidencia.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-M-d");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descInci;
    private javax.swing.JTextArea descSol;
    private javax.swing.JComboBox<String> dispositivoComboBox;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JComboBox<String> espacioComboBox;
    private javax.swing.JFormattedTextField fCierre;
    private javax.swing.JFormattedTextField fEntrada;
    private javax.swing.JComboBox<String> gestorComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> tecnicoComboBox;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textTipo;
    private javax.swing.JComboBox<String> usuarioComboBox;
    // End of variables declaration//GEN-END:variables
}
