/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ifrr.ticketing.swing;

import com.ifrr.ticketing.entities.Usuario;
import com.ifrr.ticketing.service.ServiceUsuario;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nakayoshi_dango
 */
public class CreateUsuario extends javax.swing.JDialog {

    private final ServiceUsuario su;

    /**
     * Creates new form CreateIncidencia
     */

    public CreateUsuario(java.awt.Frame parent, boolean modal, ServiceUsuario su) {
        super(parent, modal);
        this.su = su;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        textNombreLogin = new javax.swing.JTextField();
        textContrasena = new javax.swing.JTextField();
        textNombreApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        checkUsuario = new javax.swing.JCheckBox();
        checkTecnico = new javax.swing.JCheckBox();
        checkGestor = new javax.swing.JCheckBox();
        checkAdministrador = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 297));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Nombre Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Nombre Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        botonCrear.setBackground(new java.awt.Color(153, 204, 255));
        botonCrear.setText("Crear Usuario");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 260, -1, -1));

        textNombreLogin.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textNombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        textContrasena.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        textNombreApellidos.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        textCorreo.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));

        textTelefono.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel1.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        checkUsuario.setBackground(new java.awt.Color(102, 102, 255));
        checkUsuario.setForeground(new java.awt.Color(242, 242, 242));
        checkUsuario.setText("Usuario básico");
        jPanel1.add(checkUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        checkTecnico.setBackground(new java.awt.Color(102, 102, 255));
        checkTecnico.setForeground(new java.awt.Color(242, 242, 242));
        checkTecnico.setText("Técnico");
        jPanel1.add(checkTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        checkGestor.setBackground(new java.awt.Color(102, 102, 255));
        checkGestor.setForeground(new java.awt.Color(242, 242, 242));
        checkGestor.setText("Gestor");
        jPanel1.add(checkGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        checkAdministrador.setBackground(new java.awt.Color(102, 102, 255));
        checkAdministrador.setForeground(new java.awt.Color(242, 242, 242));
        checkAdministrador.setText("Administrador");
        jPanel1.add(checkAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Perfiles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        if (!textNombreLogin.getText().isBlank() && !textContrasena.getText().isBlank() && !textNombreApellidos.getText().isBlank()) {
            Integer telef = null;
            if (!textTelefono.getText().isBlank() && !textTelefono.getText().matches("([a-z]|[A-Z])")) {
                telef = Integer.valueOf(textTelefono.getText());
            }
            String correo = null;
            if (!textCorreo.getText().isBlank()) {
                correo = textCorreo.getText();
            }
            Usuario us = new Usuario(textNombreLogin.getText(), textContrasena.getText(), textNombreApellidos.getText(), correo, telef);
            List<Integer> perfiles = new ArrayList<>();
            if (checkUsuario.isSelected()) {
                perfiles.add(1);
            }
            if (checkTecnico.isSelected()) {
                perfiles.add(2);
            }
            if (checkGestor.isSelected()) {
                perfiles.add(3);
            }
            if (checkAdministrador.isSelected()) {
                perfiles.add(4);
            }
            Integer[] perfilesArr = perfiles.toArray(new Integer[0]);
            us = su.createUsuario(us, (Integer[]) perfilesArr);
            if (us != null) {
                dispose();
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "No se pudo crear el usuario.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            }
            
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Los campos nombre login, contraseña y nombre apellidos son obligatorios.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_botonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JCheckBox checkAdministrador;
    private javax.swing.JCheckBox checkGestor;
    private javax.swing.JCheckBox checkTecnico;
    private javax.swing.JCheckBox checkUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textContrasena;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textNombreApellidos;
    private javax.swing.JTextField textNombreLogin;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
