package com.ifrr.ticketing.swing;

import com.ifrr.ticketing.entities.Incidencia;
import com.ifrr.ticketing.entities.Perfil;
import com.ifrr.ticketing.entities.Usuario;
import com.ifrr.ticketing.service.ServiceIncidencia;
import com.ifrr.ticketing.service.ServiceUsuario;
import java.awt.Component;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.net.URL;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class GestorForm extends javax.swing.JFrame {

    /**
     * Creates new form Gestor
     */
    private final ServiceUsuario su;
    private final ServiceIncidencia si;
    private final Integer usuarioId;

    public GestorForm(ServiceUsuario su, ServiceIncidencia si, Integer usuarioId) {
        this.su = su;
        this.si = si;
        this.usuarioId = usuarioId;
        initComponents();
        loadComboBoxData();
    }

    private void loadComboBoxData() {
        List<Usuario> usuarios = su.getAllUsuarios();
        for (Usuario u : usuarios) {
            Set<Perfil> perfiles = u.getPerfiles();
            boolean esTecnico = false;

            for (Perfil p : perfiles) {
                if (p.getId() == 2) {
                    esTecnico = true;
                }
            }

            String item = u.getId() + ";" + u.getNombreApellidos() + ";" + u.getCorreo();

            if (esTecnico) {
                tecnicoComboBox.addItem(item);
                listTecnicoComboBox.addItem(item);
            }
        }
        HashSet<String> tipos = new HashSet<>();
        for (Incidencia in : si.getAllIncidencias()) {
            tipos.add(in.getTipo());
        }
        for (String tipo : tipos) {
            tipoComboBox.addItem(tipo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        asignarTecnico = new javax.swing.JButton();
        jScrollPaneTablaGestor = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        listarEnEspera = new javax.swing.JButton();
        listarPorTipo = new javax.swing.JButton();
        listarPorTecnico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        darDeAlta = new javax.swing.JButton();
        detallesIncidencia = new javax.swing.JButton();
        tecnicoComboBox = new javax.swing.JComboBox<>();
        listTecnicoComboBox = new javax.swing.JComboBox<>();
        tipoComboBox = new javax.swing.JComboBox<>();
        listarAsignadas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(978, 571));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(978, 571));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Bienvenido gestor!");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 200));

        asignarTecnico.setBackground(new java.awt.Color(153, 204, 255));
        asignarTecnico.setText("Asignar técnico");
        asignarTecnico.setMaximumSize(new java.awt.Dimension(163, 62));
        asignarTecnico.setMinimumSize(new java.awt.Dimension(163, 62));
        asignarTecnico.setPreferredSize(new java.awt.Dimension(163, 62));
        asignarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarTecnicoActionPerformed(evt);
            }
        });

        tablita.setBackground(new java.awt.Color(153, 204, 255));
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estado", "Desc."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablitaMousePressed(evt);
            }
        });
        jScrollPaneTablaGestor.setViewportView(tablita);
        updateTable(strFilter);

        listarEnEspera.setBackground(new java.awt.Color(153, 204, 255));
        listarEnEspera.setText("Incidencias en espera");
        listarEnEspera.setMaximumSize(new java.awt.Dimension(219, 54));
        listarEnEspera.setMinimumSize(new java.awt.Dimension(219, 54));
        listarEnEspera.setPreferredSize(new java.awt.Dimension(219, 54));
        listarEnEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEnEsperaActionPerformed(evt);
            }
        });

        listarPorTipo.setBackground(new java.awt.Color(153, 204, 255));
        listarPorTipo.setText("Incidencias por tipo");
        listarPorTipo.setMaximumSize(new java.awt.Dimension(219, 54));
        listarPorTipo.setMinimumSize(new java.awt.Dimension(219, 54));
        listarPorTipo.setPreferredSize(new java.awt.Dimension(219, 54));
        listarPorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPorTipoActionPerformed(evt);
            }
        });

        listarPorTecnico.setBackground(new java.awt.Color(153, 204, 255));
        listarPorTecnico.setText("Incidencias por técnico");
        listarPorTecnico.setMaximumSize(new java.awt.Dimension(219, 54));
        listarPorTecnico.setMinimumSize(new java.awt.Dimension(219, 54));
        listarPorTecnico.setPreferredSize(new java.awt.Dimension(219, 54));
        listarPorTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPorTecnicoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Tipo:");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Id técnico:");

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Id técnico:");

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Listar");

        darDeAlta.setBackground(new java.awt.Color(153, 204, 255));
        darDeAlta.setText("Dar de alta");
        darDeAlta.setMaximumSize(new java.awt.Dimension(163, 62));
        darDeAlta.setMinimumSize(new java.awt.Dimension(163, 62));
        darDeAlta.setPreferredSize(new java.awt.Dimension(163, 62));
        darDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeAltaActionPerformed(evt);
            }
        });

        detallesIncidencia.setBackground(new java.awt.Color(153, 204, 255));
        detallesIncidencia.setText("Detalles de incidencia");
        detallesIncidencia.setMaximumSize(new java.awt.Dimension(163, 62));
        detallesIncidencia.setMinimumSize(new java.awt.Dimension(163, 62));
        detallesIncidencia.setPreferredSize(new java.awt.Dimension(163, 62));
        detallesIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesIncidenciaActionPerformed(evt);
            }
        });

        listarAsignadas.setBackground(new java.awt.Color(153, 204, 255));
        listarAsignadas.setText("Incidencias asignadas");
        listarAsignadas.setMaximumSize(new java.awt.Dimension(219, 54));
        listarAsignadas.setMinimumSize(new java.awt.Dimension(219, 54));
        listarAsignadas.setPreferredSize(new java.awt.Dimension(219, 54));
        listarAsignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAsignadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asignarTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(darDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detallesIncidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tecnicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneTablaGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listarAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(listarPorTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarEnEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarPorTecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listTecnicoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(darDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tecnicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(asignarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(detallesIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPaneTablaGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listarEnEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listarPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listTecnicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPorTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        menuAyuda.setText("Ayuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem1);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            File f = new File("help" + File.separator + "help_set.hs");
            URL hsURL = f.toURI().toURL();
            HelpSet hs = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = hs.createHelpBroker();
            hb.enableHelpOnButton(jMenuItem1, "main", hs);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void detallesIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesIncidenciaActionPerformed
        if (idSeleccionada != null) {
            Incidencia seleccionada = si.getIncidenciaById(idSeleccionada);
            String dispositivo = "";
            String espacio = "";
            String tecnico = "";
            String gestor = "";
            String usuario = "";
            if (seleccionada.getDispositivo() != null) {
                dispositivo = seleccionada.getDispositivo().getMarca() + " " + seleccionada.getDispositivo().getModelo();
            }
            if (seleccionada.getEspacio() != null) {
                espacio = seleccionada.getEspacio().getDescripcion();
            }
            if (seleccionada.getTecnico() != null) {
                tecnico = seleccionada.getTecnico().getNombreApellidos();
            }
            if (seleccionada.getGestor() != null) {
                gestor = seleccionada.getGestor().getNombreApellidos();
            }
            if (seleccionada.getUsuario() != null) {
                usuario = seleccionada.getUsuario().getNombreApellidos();
            }
            JOptionPane.showMessageDialog(
                    null,
                    "ID: " + seleccionada.getId()
                    + "\nEstado: " + seleccionada.getEstado()
                    + "\nTipo: " + seleccionada.getTipo()
                    + "\nDescripción Incidencia: " + seleccionada.getDescIncidencia()
                    + "\nFecha de Entrada: " + seleccionada.getfEntrada()
                    + "\nFecha de Cierre: " + seleccionada.getfCierre()
                    + "\nDescripción Solución: " + seleccionada.getDescSolucion()
                    + "\nDispositivo: " + dispositivo
                    + "\nEspacio: " + espacio
                    + "\nTécnico: " + tecnico
                    + "\nGestor: " + gestor
                    + "\nUsuario: " + usuario,
                    "Detalles de incidencia",
                    JOptionPane.INFORMATION_MESSAGE
            );
            updateTable(strFilter);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, selecciona una incidencia antes de pulsar el botón",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_detallesIncidenciaActionPerformed

    private void darDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeAltaActionPerformed
        if (idSeleccionada != null) {
            Incidencia seleccionada = si.getIncidenciaById(idSeleccionada);
            if (seleccionada != null) {
                if (seleccionada.getEstado().contains("espera")) {
                    seleccionada.setEstado("aprobada");
                    si.updateIncidencia(seleccionada);
                }
            }
            updateTable(strFilter);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, selecciona una incidencia antes de pulsar el botón",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_darDeAltaActionPerformed

    private void asignarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarTecnicoActionPerformed
        if (idSeleccionada != null) {
            Incidencia seleccionada = si.getIncidenciaById(idSeleccionada);
            if (seleccionada != null) {
                String selectedTecnico = (String) tecnicoComboBox.getSelectedItem();
                if (selectedTecnico != null) {
                    int tecnicoId = Integer.parseInt(selectedTecnico.split(";")[0]);
                    seleccionada.setTecnico(su.getUsuarioById(tecnicoId));
                    si.updateIncidencia(seleccionada);
                }
            }
            updateTable(strFilter);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, selecciona una incidencia antes de pulsar el botón",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_asignarTecnicoActionPerformed

    private void listarEnEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEnEsperaActionPerformed
        strFilter = "espera";
        updateTable(strFilter);
    }//GEN-LAST:event_listarEnEsperaActionPerformed

    private void listarPorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPorTipoActionPerformed
        if ((String) tipoComboBox.getSelectedItem()!=null) {
            strFilter = "tipo";
            updateTable(strFilter);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, introduzca un tipo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_listarPorTipoActionPerformed

    private void listarPorTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPorTecnicoActionPerformed
        if ((String) listTecnicoComboBox.getSelectedItem()!=null) {
            strFilter = "tecnico";
            updateTable(strFilter);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, introduzca un id válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_listarPorTecnicoActionPerformed

    private void tablitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablitaMousePressed
        JTable source = (JTable) evt.getSource();
        int fila = source.rowAtPoint(evt.getPoint());
        idSeleccionada = (Integer) source.getModel().getValueAt(fila, 0);
    }//GEN-LAST:event_tablitaMousePressed

    private void listarAsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAsignadasActionPerformed
        strFilter = "todas";
        updateTable(strFilter);
    }//GEN-LAST:event_listarAsignadasActionPerformed

    private void updateTable(String filtro) {
        try {
            DefaultTableModel dtm = new DefaultTableModel(new Object[][]{}, new String[]{"ID", "Estado", "Desc."});
            Object[] arr;
            List<Incidencia> incidencias = si.getAllIncidencias();
            for (Incidencia incidencia : incidencias) {
                if (incidencia.getGestor() != null) {
                    if (incidencia.getGestor().getId().equals(usuarioId)) {
                        if (filtro.equals("todas")
                                || (filtro.equals("espera") && incidencia.getEstado().contains("espera"))
                                || (filtro.equals("tipo") && Objects.equals(incidencia.getTipo(), (String) tipoComboBox.getSelectedItem()))
                                || (filtro.equals("tecnico") && Objects.equals(incidencia.getTecnico().getId(), Integer.valueOf(((String) listTecnicoComboBox.getSelectedItem()).split(";")[0])))) {
                            arr = new Object[]{incidencia.getId(), incidencia.getEstado(), incidencia.getDescIncidencia()};
                            dtm.addRow(arr);
                        }
                    }
                }
            }
            tablita.setModel(dtm);
            tablita.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                    // Get the ID of the row's corresponding incidencia
                    String estado = incidencias.get(row).getEstado();

                    // Make text bold if ID is in reaperturas
                    if (estado.contains("reapertura")) {
                        cell.setFont(cell.getFont().deriveFont(Font.BOLD));
                    } else if (estado.contains("espera")) {
                        cell.setFont(cell.getFont().deriveFont(Font.ITALIC));
                    } else {
                        cell.setFont(cell.getFont().deriveFont(Font.PLAIN));
                    }
                    return cell;
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Ha habido un error actualizando la tabla: \n" + Arrays.toString(e.getStackTrace()),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    Integer idSeleccionada;
    String strFilter = "todas";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarTecnico;
    private javax.swing.JButton darDeAlta;
    private javax.swing.JButton detallesIncidencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneTablaGestor;
    private javax.swing.JComboBox<String> listTecnicoComboBox;
    private javax.swing.JButton listarAsignadas;
    private javax.swing.JButton listarEnEspera;
    private javax.swing.JButton listarPorTecnico;
    private javax.swing.JButton listarPorTipo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JTable tablita;
    private javax.swing.JComboBox<String> tecnicoComboBox;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
