/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ifrr.ticketing.swing;

import com.ifrr.ticketing.entities.Perfil;
import com.ifrr.ticketing.entities.Usuario;
import com.ifrr.ticketing.service.ServicePerfil;
import com.ifrr.ticketing.service.ServiceUsuario;
import java.util.List;
import java.util.Set;

/**
 *
 * @author tarde
 */
public class Login extends javax.swing.JDialog {

    private boolean loginSuccessful = false;
    private String perfilUsuario = "";
    private Integer idUsuario = null;
    private final ServiceUsuario su;

    /**
     * Creates new form Login
     */

    public Login(java.awt.Frame parent, ServiceUsuario su, ServicePerfil sp) {
        super(parent, true);
        this.su = su;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        exceptionLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Mono", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ticketing");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 333, 81));

        jTextField1.setToolTipText("Login Username");
        jTextField1.setPreferredSize(new java.awt.Dimension(333, 24));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Técnico", "Gestor", "Administrador" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 240, 100, -1));
        jPanel1.add(exceptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 330, 80));

        jPasswordField1.setToolTipText("Login Password");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(333, 24));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuarioInput = jTextField1.getText();
        String contrasenaInput = new String(jPasswordField1.getPassword());
        String perfilInput = (String) jComboBox1.getSelectedItem();
        if (usuarioInput.isBlank() || contrasenaInput.isBlank()) {
            exceptionLabel.setText("ERROR: Campo de usuario o contraseña vacío");
        } else {
            if (autenticar(usuarioInput, contrasenaInput, perfilInput)) {
                this.loginSuccessful = true;
                this.dispose();
            } else {
                jPasswordField1.setText("");
                exceptionLabel.setText("ERROR: Usuario, contraseña o tipo de perfil incorrecto.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private boolean autenticar(String username, String password, String perfil) {

        /* 
           Juzgar si el usuario con el nombre de login indicado tiene la contraseña indicada
           El this.perfilUsuario se concretará con un spinner. 
           Si el usuario indicado tiene el perfil del spinner y el login es exitoso,
           cambiar la variable this.perfilUsuario por el perfil que tenga el spinner 
           y returnear true.
           Si no lo es, returnea false y cambiar el contenido del label a "Error"
         */
        List<Usuario> users = su.getAllUsuarios();
        for (Usuario user : users) {
            if (user.getNombreLogin().equals(username)) {
                if (user.getContrasena().equals(password)) {
                    Set<Perfil> perfiles = user.getPerfiles();
                    for (Perfil p : perfiles) {
                        if (p.getTipo().equals(perfil)) {
                            this.perfilUsuario = perfil;
                            this.idUsuario = user.getId();
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }

    public boolean isLoginSuccessful() {
        return loginSuccessful;
    }

    public String getPerfilUsuario() {
        return perfilUsuario;
    }
    
    public Integer getIdUsuario() {
        return idUsuario;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exceptionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
